<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <!-- Restore from build.yml's current RustODotnet nupkg artifact. -->
    <PackageReference Include="RustODotnet" Version="0.2.2" />
  </ItemGroup>
</Project>
